---
title: "February 14 Update"
author: "Team 8 Cohort A"
date: "2/12/2020"
output: pdf_document
---

```{r}
library(tidyverse)
library(rvest)
library(tidytext)
library(wordcloud)
library(quanteda)
library(quanteda.corpora)
library(openair)
library(lubridate)
library(prophet)
library(corrplot)
library(skimr)

sp500 <- read.csv('timeseries_analysis/S&P500Index.csv')
nyse <- read.csv('timeseries_analysis/NYSE.csv')
nasdaq <- read.csv('timeseries_analysis/NASDAQ.csv')
DJ <- read.csv('timeseries_analysis/NASDAQ.csv')
```

```{r}
#install.packages("twitteR")
library(twitteR)

consumer_key <- "Db9ShtReQqwmnwfPlN80rYX3Y"
consumer_secret <- "8eqP5nYdOyXv1AcSB4ofYO63GwaDMV0LVgYoei9GPjozHPjk08"
access_token <- "1227999098881617921-mbvxI5Slq76GAr3m4nS8eAv2esZq8r"
access_secret <- "3f4f5d8S7RGbI4QXE1TCNq4krgUe2UKcAyZNvzMd0uVUN"

setup_twitter_oauth(consumer_key, consumer_secret, access_token, access_secret)

tweets <- searchTwitter('S&P500', n = 1368, lang = 'en') # 1368 is max the api can return
tweetsdf <- twListToDF(tweets)
tweetsold <- read.csv('sentiment_analysis/tweets_feb_14_pull.csv')
x <- rbind(tweetsdf, tweetsold)
x <- x %>% filter(isRetweet == 'TRUE')
write.csv(x, file = 'sentiment_analysis/tweets')

```
```{r}
sp <- transform(sp500, date = as.Date(as.character(sp500$caldt), "%Y%m%d"))

ggplot(data = sp, aes(x = date, y = spindx)) +
  geom_line(color = "#FC4E07") +
  labs(title = "1990 - 2019 S&P500 Price")

```
